2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_setup.py:_flush():76] Configure stats pid to 811
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_setup.py:_flush():76] Loading settings from /root/proj2/wandb/settings
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'personalized_automate.py', 'program': '/root/proj2/personalized_automate.py'}
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_init.py:_log_setup():507] Logging user logs to /root/proj2/wandb/run-20230701_201345-lzeqtavd/logs/debug.log
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_init.py:_log_setup():508] Logging internal logs to /root/proj2/wandb/run-20230701_201345-lzeqtavd/logs/debug-internal.log
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_init.py:init():547] calling init triggers
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'depth': 3, 'lr': 6.481460531048047e-06, 'epochs': 40000, 'batch_size': 35, 'hidden_dim': 23}
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_init.py:init():571] re-initializing run, found existing run on stack: jpnd2pfy
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_run.py:_finish():1893] finishing run jli505/unet_ssl/jpnd2pfy
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_run.py:_atexit_cleanup():2127] got exitcode: 0
2023-07-01 20:13:45,642 INFO    MainThread:811 [wandb_run.py:_restore():2110] restore
2023-07-01 20:13:45,643 INFO    MainThread:811 [wandb_run.py:_restore():2116] restore done
2023-07-01 20:13:48,693 INFO    MainThread:811 [wandb_run.py:_footer_history_summary_info():3469] rendering history
2023-07-01 20:13:48,693 INFO    MainThread:811 [wandb_run.py:_footer_history_summary_info():3501] rendering summary
2023-07-01 20:13:48,694 INFO    MainThread:811 [wandb_run.py:_footer_sync_info():3428] logging synced files
2023-07-01 20:13:48,801 INFO    MainThread:811 [wandb_init.py:init():596] starting backend
2023-07-01 20:13:48,801 INFO    MainThread:811 [wandb_init.py:init():600] setting up manager
2023-07-01 20:13:48,803 INFO    MainThread:811 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-07-01 20:13:48,804 INFO    MainThread:811 [wandb_init.py:init():606] backend started and connected
2023-07-01 20:13:48,805 INFO    MainThread:811 [wandb_init.py:init():700] updated telemetry
2023-07-01 20:13:48,806 INFO    MainThread:811 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-07-01 20:13:49,938 INFO    MainThread:811 [wandb_run.py:_on_init():2177] communicating current version
2023-07-01 20:13:50,012 INFO    MainThread:811 [wandb_run.py:_on_init():2186] got version response upgrade_message: "wandb version 0.15.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-07-01 20:13:50,012 INFO    MainThread:811 [wandb_init.py:init():787] starting run threads in backend
2023-07-01 20:13:51,638 INFO    MainThread:811 [wandb_run.py:_console_start():2158] atexit reg
2023-07-01 20:13:51,638 INFO    MainThread:811 [wandb_run.py:_redirect():2013] redirect: SettingsConsole.WRAP_RAW
2023-07-01 20:13:51,638 INFO    MainThread:811 [wandb_run.py:_redirect():2078] Wrapping output streams.
2023-07-01 20:13:51,638 INFO    MainThread:811 [wandb_run.py:_redirect():2103] Redirects installed.
2023-07-01 20:13:51,638 INFO    MainThread:811 [wandb_init.py:init():829] run started, returning control to user process
2023-07-01 20:18:22,144 WARNING MsgRouterThr:811 [router.py:message_loop():77] message_loop has been closed
